### ISSUE TITLE
Improve reporting

### ISSUE THREAD

**Issue by nictru** [nf-core/scdownstream#2]
### Description of feature

Example reporting has already been implemented [here](https://github.com/nf-core/scdownstream/blob/dev/modules/local/scanpy/plotqc/templates/plotqc.py). scFlow had really nice reports that should be used as inspiration (can be viewed [here](https://drive.google.com/drive/folders/1pZeTy_yDlGY5-IxxYCHO7xi-4KqJJ2Fk?usp=drive_link)).

**Comment by nictru** [comment]
If you want to contribute here, adding plots of the UMAP representations of the integrations to the report would be a good starting point. UMAP creation currently happens in [this module](https://github.com/nf-core/scdownstream/tree/dev/modules/local/scanpy/umap), more specifically in [this script](https://github.com/nf-core/scdownstream/blob/dev/modules/local/scanpy/umap/templates/umap.py). After [this line](https://github.com/nf-core/scdownstream/blob/ed86d623263af3773c4514eac19d1509a869e1a1/modules/local/scanpy/umap/templates/umap.py#L33), the `X_umap` obsm field will contain the proper representation that can directly used for plotting.

Plotting itself should not be much of a problem. Make sure to use `${prefix}.png` as the plot file name. In order to properly add the plots to the multiQC report, some additional steps are required:
1. Create a json file like it is done [here](https://github.com/nf-core/scdownstream/blob/ed86d623263af3773c4514eac19d1509a869e1a1/modules/local/scanpy/plotqc/templates/plotqc.py#L37)
2. Change the output definition of the `UMAP` process so that the png and json are emitted properly ([example](https://github.com/nf-core/scdownstream/blob/ed86d623263af3773c4514eac19d1509a869e1a1/modules/local/scanpy/plotqc/main.nf#L13))
3. Add a new channel to the [`CLUSTER`](https://github.com/nf-core/scdownstream/blob/dev/subworkflows/local/cluster.nf) subworkflow called `ch_multiqc_files` like [here](https://github.com/nf-core/scdownstream/blob/ed86d623263af3773c4514eac19d1509a869e1a1/subworkflows/local/doublet_detection.nf#L14C5-L14C21). Make sure to mix in the json outputs and emit the channel in the end of the `CLUSTER` subworkflow
4. Mix the subworkflow `ch_multiqc_files` into the global one like [here](https://github.com/nf-core/scdownstream/blob/ed86d623263af3773c4514eac19d1509a869e1a1/workflows/scdownstream.nf#L43)
5. If necessary, adjust the [multiQC config](https://github.com/nf-core/scdownstream/blob/dev/assets/multiqc_config.yml). General information on MultiQC can be found in [the docs](https://multiqc.info/docs/custom_content/).

PS:
Because of the way the [`CLUSTER` subworkflow](https://github.com/nf-core/scdownstream/blob/dev/subworkflows/local/cluster.nf) is structured, you can be sure that the neighborhood graph that is used as a base for UMAP creation is based on the correct embeddings.

**Comment by paulinefx** [comment]
Things to improve:

- [x] Order of the results in the multiQC report
- [x] Add description
