### ISSUE TITLE
Implement GPU support for relevant tools

### ISSUE THREAD

**Issue by nictru** [nf-core/scdownstream#69]
### Description of feature

As discussed in #68. Should start with SCVI first, as it is probably most relevant. Inspiration for implementation can be taken from #proteinfold. Should try to establish common guidelines for GPU support.

**Comment by fbnrst** [comment]
I believe cellbender is another candidate for GPU support. Today, I managed to hack this in, by adding the following to a config file:

```nextflow
process {
    executor = 'slurm'
    withName: '.*:EMPTY_DROPLET_REMOVAL:CELLBENDER_REMOVEBACKGROUND' {
        cpus = 1
        debug = true
        container = 'docker://us.gcr.io/broad-dsde-methods/cellbender:0.3.2'
        queue = "gpu"
        clusterOptions = '--gres=gpu:1'
        ext.args = { "--epochs ${params.cellbender_epochs} --cuda" }
    }
}

singularity {
  enabled=true
  runOptions    = '--no-mount tmp --writable-tmpfs --nv'
}
```

Here, I am using a GPU enabled docker container that is provided by the cellbender developers.

**Comment by nictru** [comment]
Thanks for the input. In the meantime I had a discussion with other maintainers concerning standardization and this is my best plan for now:

1. Add a label `process_gpu` to all processes supporting GPU
2. Add a profile `gpu` which does the following:
    - For all processes `withLabel: "process_gpu"` set `ext.use_gpu` to equal true
    - Tell containerization engines to mount GPUs (e.g. `apptainer.runOptions = "--nv"` ). As far as I know these runOptions can only be set globally not per process/task. However, this will not have any negative effect on processes that don't utilize GPU.
5. Not sure about this one: Switch the environment based on ext.use_gpu as the images containing GPU drivers will be much larger than the non-GPU ones and not everyone will need them
6. Within the script , utilize ext.use_gpu to tell the underlying tool to use GPU or not (e.g. adding `--cuda`)

Which leaves the following for the user:

- Set a different queue for all processes `withLabel: "process_gpu"`
- Adjust the `clusterOptions` to run the tasks on GPU nodes

**Comment by fbnrst** [comment]
Maybe this could be of help when implementing, only relevant for slurm+singularity:

When running the hack above, I did run in some GPU memory issues. I realised that I had 8 jobs running, but they all used the same gpu. I think I tracked this down to the following: slurm set the variable `CUDA_VISIBLE_DEVICES` to assign GPUs to a job. But inside the singularity container this variable is not visible anymore, probably because it is started in contained mode. So, this variable has to be passed to inside the container (not sure yet how), such that jobs are properly distributed to different GPUs.

**Comment by fbnrst** [comment]
Regarding my last comment, I solved this by explicitly setting passing some variables into the container using the `--env` flag:
```
singularity {
  enabled=true
  runOptions    = '--no-mount tmp --writable-tmpfs --nv --env CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES --env ROCR_VISIBLE_DEVICES=$ROCR_VISIBLE_DEVICES --env ZE_AFFINITY_MASK=$ZE_AFFINITY_MASK --env NVIDIA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES'
}
```
