### ISSUE TITLE
additional output for cellbender

### ISSUE THREAD

**Issue by fbnrst** [nf-core/scdownstream#75]
### Description of feature

cellbender produces some outputs which are neccesary for QC (https://cellbender.readthedocs.io/en/latest/usage/index.html#quality-control-checks), e.g. `output_report.html`, `output.log` and `output.pdf`. It would be great to add them to the output, would you agree? I just looked at some of them in an analysis of mine and realised cellbender did not converge for some samples.

**Comment by nictru** [comment]
Yes, can easily to that after [this PR](https://github.com/nf-core/modules/pull/6155) has been merged.
