### ISSUE TITLE
Pipeline not running correctly on GPU 

### ISSUE THREAD

**Issue by pakiessling** [nf-core/scdownstream#90]
### Description of the bug

Hi, thank you for the tool, super cool!
Runs very well on CPU, but not GPU.
There the pipeline gets stuck after `SCDOWNSTREAM:PREPROCESS:DOUBLET_DETECTION:DOUBLETDETECTION`
I assume this is where GPU is needed for the first time.
Here I just see:
`executor slurm > No more task to compute -- The following nodes are still active:`
and then all the missing steps.

I see no error messages.

Any ideas?

### Command used and terminal output

```console
source /work/mz637064/miniconda3/bin/activate /hpcwork/p0020567/enviroments/nf
export JAVA_HOME="/hpcwork/p0020567/enviroments/nf/lib/jvm"
export NXF_SINGULARITY_CACHEDIR="/hpcwork/p0020567/software/singularity_cache"
export SINGULARITY_TMPDIR="/hpcwork/p0020567/software/singularity_tmp"
export SINGULARITY_CACHEDIR="/hpcwork/p0020567/software/singularity_cache"

nextflow run /work/rwth1209/projects/spatial_infarct-2024-tmp/nf_core_scrna/scdownstream/main.nf --input ./samplesheet.csv --outdir ./results  -profile singularity,gpu -w /hpcwork/mz637064/cache -bg -resume -c params.config \
--ambient_removal decontx --doublet_detection "scrublet,doubletdetection" \
--celltypist_model "Healthy_Adult_Heart" > master.log 2>&1
```

### Relevant files

[nextflow.log](https://github.com/user-attachments/files/17012296/nextflow.log)
[params.txt](https://github.com/user-attachments/files/17012301/params.txt)

### System information

Singularity
CentOS
HPC
Nextflow 24.04.4.5917
slurm

**Comment by nictru** [comment]
So basically the `scrublet` process does not terminate. Did you check the jobs state in the slurm queue (`squeue`)? My current guess is that slurm has troubles finding an appropriate node to execute the task on.

**Comment by pakiessling** [comment]
Yeah I checked. There were no active / pending jobs and I waited around an hour.

Is scrublet the first process running on gpu? Then I might need to check the Slurm > GPU node configuration.

To doublecheck supplying a file with `-c`
containing:
```
process {
  withLabel:process_gpu {
    queue = 'c23g'
    clusterOptions = '--gpus 1'
  }
}
```

where I would call slurm like this:

```
#SBATCH --partition=c23g
#SBATCH --gpus-per-node=1
```

Is the correct way to use GPU nodes with Slurm?

**Comment by pakiessling** [comment]
Ah okay. It needs to be specifically:

```
process {
  withLabel:process_gpu {
    queue = 'c23g'
    clusterOptions = '--gpus-per-node=1'
  }
}

executor {
  account = "project account"
}
```

At least on our SLURM version

**Comment by nictru** [comment]
Ok I just wanted to tell you :) I can updated the documentation to guide users a bit more, for now I just wrote there what works on my cluster

**Comment by pakiessling** [comment]
Yeah that's fair nothing to do with your tool in particular
